### ISSUE TITLE
Run GCC C regression tests on CI

### ISSUE THREAD

**Issue by ibolton** [riscvarchive/riscv-dejagnu#4]
With the addition of the riscv-spike.exp, we can now easily run all 87000 GCC C regression tests through spike via a one-line "make check-gcc-c ..." in the appropriate directory. It would be good to have these tests run after builds of the toolchain, so we can track and detect failures. We have a simple script that does this in our embecosm/riscv-toolchain repo, which you are welcome to borrow/adapt.

**Comment by jim-wilson** [comment]
I see that a riscv-spike.exp file was added about 7 months ago.
